set-environment TERM_BACKGROUND dark
set-environment BAT_THEME OneHalfDark
set-environment FZF_DEFAULT_OPTS '--prompt="❯ "'
set-environment -F LG_CONFIG_FILE "#{HOME}/AppData/Local/lazygit/config.yml,#{HOME}/AppData/Local/lazygit/config-dark.yml"
